{
 "title": "Auth Service Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "query_result(up)" } },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   },
   {
    "name": "interval",
    "query": "1h, 3h, 6h, 12h, 1d, 2d, 7d, 30d, 90d, 180d"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"auth-service:3001\", job=\"auth-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{job=\"auth-service\", instance=\"auth-service:3001\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"auth-service\", instance=\"auth-service:3001\"}) / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage collection time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{job=\"auth-service\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{job=\"auth-service\"}[5m]))/sum(rate(http_request_duration_seconds_count{job=\"auth-service\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"auth-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}