{
 "title": "Starcendence - Services - Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "query_result(up)" } },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   },
   {
    "name": "interval",
    "query": "1h, 3h, 6h, 12h, 1d, 2d, 7d, 30d, 90d, 180d"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"http-metrics\"}",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"http-metrics\"}[5m]) * 100",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"http-metrics\"}) / 3600",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{job=\"http-metrics\"}",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"http-metrics\"}",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "Phisical RAM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"http-metrics\"}",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "Total Http Requests",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{job=\"http-metrics\"}",
     "legendFormat": "{{display}}"
    }
   ]
  }
 ]
}